
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package eu.europa.ec.ecris.contract;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2021-10-13T17:44:06.419+02:00
 * Generated source version: 2.4.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "ecrisService-v1.0_nofp",
                      portName = "ecrisServicePort-v1.0",
                      targetNamespace = "http://ec.europa.eu/ECRIS/contract",
                      wsdlLocation = "file:/C:/Users/franc/AppData/Local/Temp/tempdir389853609489516388.tmp/ecris-service-v1.0_1.wsdl",
                      endpointInterface = "eu.europa.ec.ecris.contract.EcrisServicePortTypeV10")
                      
public class EcrisServicePortTypeV10Impl implements EcrisServicePortTypeV10 {

    private static final Logger LOG = Logger.getLogger(EcrisServicePortTypeV10Impl.class.getName());

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverRequestPush(eu.europa.ec.ecris.messages_v1.RequestMessagePushType  body )*
     */
    public void deliverRequestPush(eu.europa.ec.ecris.messages_v1.RequestMessagePushType body) { 
        LOG.info("Executing operation deliverRequestPush");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverRequestAdditionalInfo(eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoMessageType  body )*
     */
    public void deliverRequestAdditionalInfo(eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoMessageType body) { 
        LOG.info("Executing operation deliverRequestAdditionalInfo");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverNotification(eu.europa.ec.ecris.messages_v1.NotificationMessageType  body )*
     */
    public void deliverNotification(eu.europa.ec.ecris.messages_v1.NotificationMessageType body) { 
        LOG.info("Executing operation deliverNotification");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverRequestResponsePush(eu.europa.ec.ecris.messages_v1.RequestResponseMessagePushType  body )*
     */
    public void deliverRequestResponsePush(eu.europa.ec.ecris.messages_v1.RequestResponseMessagePushType body) { 
        LOG.info("Executing operation deliverRequestResponsePush");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverFunctionalError(eu.europa.ec.ecris.messages_v1.FunctionalErrorMessageType  body )*
     */
    public void deliverFunctionalError(eu.europa.ec.ecris.messages_v1.FunctionalErrorMessageType body) { 
        LOG.info("Executing operation deliverFunctionalError");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverNotificationResponse(eu.europa.ec.ecris.messages_v1.NotificationResponseMessageType  body )*
     */
    public void deliverNotificationResponse(eu.europa.ec.ecris.messages_v1.NotificationResponseMessageType body) { 
        LOG.info("Executing operation deliverNotificationResponse");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverRequestAdditionalInfoResponsePush(eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoResponseMessagePushType  body )*
     */
    public void deliverRequestAdditionalInfoResponsePush(eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoResponseMessagePushType body) { 
        LOG.info("Executing operation deliverRequestAdditionalInfoResponsePush");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverRequest(eu.europa.ec.ecris.messages_v1.RequestMessageType  body )*
     */
    public void deliverRequest(eu.europa.ec.ecris.messages_v1.RequestMessageType body) { 
        LOG.info("Executing operation deliverRequest");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverRequestAdditionalInfoResponse(eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoResponseMessageType  body )*
     */
    public void deliverRequestAdditionalInfoResponse(eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoResponseMessageType body) { 
        LOG.info("Executing operation deliverRequestAdditionalInfoResponse");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#isAlive(eu.europa.ec.ecris.messages_v1.IsAliveMessageType  body )*
     */
    public void isAlive(javax.xml.ws.Holder<eu.europa.ec.ecris.messages_v1.IsAliveMessageType> body) { 
        LOG.info("Executing operation isAlive");
        System.out.println(body.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverRequestDeadline(eu.europa.ec.ecris.messages_v1.RequestDeadlineMessageType  body )*
     */
    public void deliverRequestDeadline(eu.europa.ec.ecris.messages_v1.RequestDeadlineMessageType body) { 
        LOG.info("Executing operation deliverRequestDeadline");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverNotificationPush(eu.europa.ec.ecris.messages_v1.NotificationMessagePushType  body )*
     */
    public void deliverNotificationPush(eu.europa.ec.ecris.messages_v1.NotificationMessagePushType body) { 
        LOG.info("Executing operation deliverNotificationPush");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverNotificationResponsePush(eu.europa.ec.ecris.messages_v1.NotificationResponseMessagePushType  body )*
     */
    public void deliverNotificationResponsePush(eu.europa.ec.ecris.messages_v1.NotificationResponseMessagePushType body) { 
        LOG.info("Executing operation deliverNotificationResponsePush");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverRequestResponse(eu.europa.ec.ecris.messages_v1.RequestResponseMessageType  body )*
     */
    public void deliverRequestResponse(eu.europa.ec.ecris.messages_v1.RequestResponseMessageType body) { 
        LOG.info("Executing operation deliverRequestResponse");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eu.europa.ec.ecris.contract.EcrisServicePortTypeV10#deliverCancellation(eu.europa.ec.ecris.messages_v1.CancellationMessageType  body )*
     */
    public void deliverCancellation(eu.europa.ec.ecris.messages_v1.CancellationMessageType body) { 
        LOG.info("Executing operation deliverCancellation");
        System.out.println(body);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
