package eu.europa.ec.ecris.contract;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Definition of the web service operations to be used for the ECRIS data exchanges
 *
 * This class was generated by Apache CXF 2.4.6
 * 2021-10-13T17:44:06.493+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://ec.europa.eu/ECRIS/contract", name = "ecrisServicePortType-v1.0")
@XmlSeeAlso({eu.europa.ec.ecris.messages_v1.ObjectFactory.class, eu.europa.ec.ecris.service_v1.ObjectFactory.class, eu.europa.ec.ecris.common_reference_tables_v1.ObjectFactory.class, eu.europa.ec.ecris.commons_v1.ObjectFactory.class, eu.europa.ec.ecris.domain_model_v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EcrisServicePortTypeV10 {

    /**
     * "deliverRequestPush" is the entry operation of the "Request Criminal Record Information" business process ('push" version including binary attachment)
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverRequestPush")
    @Oneway
    public void deliverRequestPush(
        @WebParam(partName = "body", name = "RequestPushMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.RequestMessagePushType body
    );

    /**
     * "deliverRequestAdditionalInfo" is the entry operation for the "Search Person" sub-process and can be used in both business processes "Request Criminal Record Information" and "Notify Convictions and Subsequent Changes"
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverRequestAdditionalInfo")
    @Oneway
    public void deliverRequestAdditionalInfo(
        @WebParam(partName = "body", name = "RequestAdditionalInfoMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoMessageType body
    );

    /**
     * "deliverNotification" is the entry operation for the "Notify Convictions and Subsequent Changes" business process
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverNotification")
    @Oneway
    public void deliverNotification(
        @WebParam(partName = "body", name = "NotificationMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.NotificationMessageType body
    );

    /**
     * "deliverRequestResponsePush" is the operation that provides the business response to the request ("push" version including binary attachment)
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverRequestResponsePush")
    @Oneway
    public void deliverRequestResponsePush(
        @WebParam(partName = "body", name = "RequestResponsePushMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.RequestResponseMessagePushType body
    );

    /**
     * "deliverBinary" is the operation that provides the functional error that occurred when processing one of the business messages
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverFunctionalError")
    @Oneway
    public void deliverFunctionalError(
        @WebParam(partName = "body", name = "FunctionalErrorMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.FunctionalErrorMessageType body
    );

    /**
     * "deliverNotificationResponse" is the operation that provides the business response to the notification
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverNotificationResponse")
    @Oneway
    public void deliverNotificationResponse(
        @WebParam(partName = "body", name = "NotificationResponseMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.NotificationResponseMessageType body
    );

    /**
     * "deliverRequestAdditionalInfoResponsePush" is the operation that provides the business response to the request for additional identification information, to be used only in cases where additional ID info is available ("push" version including binary attachment)
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverRequestAdditionalInfoResponsePush")
    @Oneway
    public void deliverRequestAdditionalInfoResponsePush(
        @WebParam(partName = "body", name = "RequestAdditionalInfoResponsePushMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoResponseMessagePushType body
    );

    /**
     * "deliverRequest" is the entry operation for the "Request Criminal Record Information" business process
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverRequest")
    @Oneway
    public void deliverRequest(
        @WebParam(partName = "body", name = "RequestMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.RequestMessageType body
    );

    /**
     * "deliverRequestAdditionalInfoResponse" is the operation that provides the business response to the request for additional identification information in all cases, whether additional ID info is available or not
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverRequestAdditionalInfoResponse")
    @Oneway
    public void deliverRequestAdditionalInfoResponse(
        @WebParam(partName = "body", name = "RequestAdditionalInfoResponseMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.RequestAdditionalInfoResponseMessageType body
    );

    /**
     * "isAlive" is the operation that allows checking whether another ECRIS web service endpoint is properly responding
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/isAlive")
    public void isAlive(
        @WebParam(partName = "body", mode = WebParam.Mode.INOUT, name = "IsAliveMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        javax.xml.ws.Holder<eu.europa.ec.ecris.messages_v1.IsAliveMessageType> body
    );

    /**
     * "deliverRequestDeadline" is the operation that provides the legal deadline for the response to the request
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverRequestDeadline")
    @Oneway
    public void deliverRequestDeadline(
        @WebParam(partName = "body", name = "RequestDeadlineMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.RequestDeadlineMessageType body
    );

    /**
     * "deliverNotificationPush" is the entry operation for the "Notify Convictions and Subsequent Changes" business process ("push" version including binary attachment)
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverNotificationPush")
    @Oneway
    public void deliverNotificationPush(
        @WebParam(partName = "body", name = "NotificationPushMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.NotificationMessagePushType body
    );

    /**
     * "deliverNotificationResponse" is the operation that provides the business response to the notification ("push" version including binary attachment)
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverNotificationResponsePush")
    @Oneway
    public void deliverNotificationResponsePush(
        @WebParam(partName = "body", name = "NotificationResponsePushMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.NotificationResponseMessagePushType body
    );

    /**
     * "deliverRequestResponse" is the operation that provides the business response to the request
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverRequestResponse")
    @Oneway
    public void deliverRequestResponse(
        @WebParam(partName = "body", name = "RequestResponseMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.RequestResponseMessageType body
    );

    /**
     * "deliverCancellation" is the operation that allows cancelling a previously sent message
     */
    @WebMethod(action = "http://ec.europa.eu/ECRIS/deliverCancellation")
    @Oneway
    public void deliverCancellation(
        @WebParam(partName = "body", name = "CancellationMessage", targetNamespace = "http://ec.europa.eu/ECRIS/service-v1.0")
        eu.europa.ec.ecris.messages_v1.CancellationMessageType body
    );
}
