
package eu.europa.ec.ecris.contract;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2021-10-13T17:44:06.513+02:00
 * Generated source version: 2.4.6
 * 
 */
 
public class EcrisServicePortTypeV10_EcrisServicePortV10_Server{

    protected EcrisServicePortTypeV10_EcrisServicePortV10_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new EcrisServicePortTypeV10Impl();
        String address = "http://public.host.at.stesta/ecris";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new EcrisServicePortTypeV10_EcrisServicePortV10_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
